### ISSUE TITLE
Create Github Actions based release flow

### ISSUE THREAD

**Issue by d3mystified** [TrevTV/Lidarr.Plugin.Tidal#2]
So releases are published automatically.

**Comment by TrevTV** [comment]
This would require me to refactor how I have dependencies setup, which I don't really feel like doing. I likely won't be doing anywhere near enough releases to make it worth the effort.

**Comment by TrevTV** [comment]
@alexandru0-dev Nothing special, it's compiled through Visual Studio 2022. I have a project reference set to a clone of [this repo](https://github.com/TrevTV/TidalSharp) and use an old version of Lidarr for reference assemblies, I don't remember exactly which version it is but [here are the files](https://www.swisstransfer.com/d/651b8719-5200-4b86-a01e-143de3217377) I use.

**Comment by alexandru0-dev** [comment]
> Nothing special, it's compiled through Visual Studio 2022. I have a project reference set to a clone of [this repo](https://github.com/TrevTV/TidalSharp) and use an old version of Lidarr for reference assemblies, I don't remember exactly which version it is but [here are the files](https://www.swisstransfer.com/d/651b8719-5200-4b86-a01e-143de3217377) I use.

I'm on linux and I wanted to make it reproducible. (Premise this is my first time working with C#)
After discovering that only the sdk8+ compiles, I got it building WITHOUT ILRepack in Release (Debug doesn't work for some reason)
Is the ILRepack necessary?

**Comment by TrevTV** [comment]
> I'm on linux and I wanted to make it reproducible. (Premise this is my first time working with C#)
> After discovering that only the sdk8+ compiles, I got it building WITHOUT ILRepack in Release (Debug doesn't work for some reason)
> Is the ILRepack necessary?

Yes (or some other way to merge .NET assemblies), Lidarr's plugin system has a bug which can randomly break loading dependency assemblies so ILRepack is a workaround for that without modifying Lidarr itself.
