### ISSUE TITLE
Change quality to be bit based

### ISSUE THREAD

**Issue by d3mystified** [TrevTV/Lidarr.Plugin.Tidal#3]
Instead of Lossless, Hi-Res and Hi-Res Lossless, use "Lossless" and "24bit Lossless"?

I'm also not sure what `Hi-Res Lossless` means.

**Comment by TrevTV** [comment]
The names were based on `python-tidal` which is used in `tidal-dl-ng`
https://github.com/tamland/python-tidal/blob/master/tidalapi/media.py#L57

I may change it at some point, depends on when I get around to it.

**Comment by TrevTV** [comment]
Changed Hi-Res Lossless to 24-bit Lossless and just removed the normal Hi-Res option as apparently that's what MQA was, before Tidal removed their MQA tracks (https://github.com/tamland/python-tidal/issues/297).
