### ISSUE TITLE
Install ffmpeg in unraid?

### ISSUE THREAD

**Issue by lightsout** [TrevTV/Lidarr.Plugin.Tidal#8]
Not really an issue but I don't know where else to ask a question. I have lidarr running on unraid. Got this plugin going and it works great. But I am unsure as to how to get ffmpeg installed. 

Are you familiar with unraid? It uses a template not a usual run command. I am not sure where to put this:
"FROM ghcr.io/hotio/lidarr:pr-plugins

RUN apk add --no-cache ffmpeg"

And also the the "dockerfile" section pertains to unraid as well.

**Comment by TrevTV** [comment]
I use Docker Compose with Ubuntu server, so I don't know how it would work for Unraid

**Comment by lightsout** [comment]
All good thanks.

**Comment by christorepl** [comment]
I think I got it. I am able to download from Tidal and they import as FLAC. I opened the unRAID terminal and entered:

`docker exec lidarr apk add --no-cache ffmpeg`
